// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm5Vqb2UqoP6vHS2ZvGeiLg5rSv9b25v4',
    appId: '1:766775738380:web:bc1dacc5bc50b85768ee29',
    messagingSenderId: '766775738380',
    projectId: 'madl26-firebase-database',
    authDomain: 'madl26-firebase-database.firebaseapp.com',
    databaseURL: 'https://madl26-firebase-database-default-rtdb.firebaseio.com',
    storageBucket: 'madl26-firebase-database.firebasestorage.app',
    measurementId: 'G-T06G6XF5LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByPUtG6b0m9fDMZa_WxxRHb6lHloVDBFE',
    appId: '1:766775738380:android:96c763f66b75f9fb68ee29',
    messagingSenderId: '766775738380',
    projectId: 'madl26-firebase-database',
    databaseURL: 'https://madl26-firebase-database-default-rtdb.firebaseio.com',
    storageBucket: 'madl26-firebase-database.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwcRpIJRoRtpzjUYhuCttJCzsY7atTARI',
    appId: '1:766775738380:ios:f08c3d0e12f0520968ee29',
    messagingSenderId: '766775738380',
    projectId: 'madl26-firebase-database',
    databaseURL: 'https://madl26-firebase-database-default-rtdb.firebaseio.com',
    storageBucket: 'madl26-firebase-database.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDatabaseApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwcRpIJRoRtpzjUYhuCttJCzsY7atTARI',
    appId: '1:766775738380:ios:f08c3d0e12f0520968ee29',
    messagingSenderId: '766775738380',
    projectId: 'madl26-firebase-database',
    databaseURL: 'https://madl26-firebase-database-default-rtdb.firebaseio.com',
    storageBucket: 'madl26-firebase-database.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDatabaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm5Vqb2UqoP6vHS2ZvGeiLg5rSv9b25v4',
    appId: '1:766775738380:web:7689949ab236f14768ee29',
    messagingSenderId: '766775738380',
    projectId: 'madl26-firebase-database',
    authDomain: 'madl26-firebase-database.firebaseapp.com',
    databaseURL: 'https://madl26-firebase-database-default-rtdb.firebaseio.com',
    storageBucket: 'madl26-firebase-database.firebasestorage.app',
    measurementId: 'G-XG63HE0MTE',
  );
}
